############### 默认配置

#spring配置
spring:
  #freemarker
  freemarker:
    charset: UTF-8
    # 是否启用模板缓存。
    enabled: true
    suffix: .ftl
    template-loader-path: /template-ftl
    settings:
      classic_compatible: true
    check-template-location: false
    cache: false

server:
  port: 8080
  servlet:
    context-path: /snackpub